const cards = [
  {
    id: 1,
    tag: "React",
    title: "React hooks deep dive",
    description: "How useState, useEffect and custom hooks work under the hood — and when to use each one.",
    date: "Mar 12, 2025",
    tagColor: "#E0F2FE",
    tagText: "#075985",
    accentColor: "#0284c7",
    iconColor: "#0284c7",
    bgColor: "#E0F2FE",
  },
  {
    id: 2,
    tag: "Python",
    title: "Python for beginners",
    description: "The core concepts every Python developer needs — loops, functions, and data structures explained simply.",
    date: "Feb 4, 2025",
    tagColor: "#DCFCE7",
    tagText: "#15803d",
    accentColor: "#16a34a",
    iconColor: "#16a34a",
    bgColor: "#DCFCE7",
  },
  {
    id: 3,
    tag: "TypeScript",
    title: "TypeScript tricks I use daily",
    description: "Utility types, narrowing patterns, and generics that make your code bulletproof and easier to read.",
    date: "Jan 20, 2025",
    tagColor: "#FEF9C3",
    tagText: "#92400e",
    accentColor: "#ca8a04",
    iconColor: "#ca8a04",
    bgColor: "#FEF9C3",
  },
  {
    id: 4,
    tag: "CSS",
    title: "CSS animations that don't hurt",
    description: "Smooth, performant transitions using only transform and opacity. No jank, no layout thrashing, ever.",
    date: "Dec 9, 2024",
    tagColor: "#F3E8FF",
    tagText: "#7e22ce",
    accentColor: "#9333ea",
    iconColor: "#9333ea",
    bgColor: "#F3E8FF",
  },
];

export default cards;