const cards = [
  {
    id: 1,
    tag: "React",
    title: "Problem I solved with React",
    problem: "My component kept re-rendering unnecessarily.",
    solution: "Used useCallback to memoize the function and fixed it.",
    date: "Mar 12, 2025",
    tagColor: "#E0F2FE",
    tagText: "#075985",
    accentColor: "#0284c7",
    iconColor: "#0284c7",
    bgColor: "#E0F2FE",
  },
  {
    id: 2,
    tag: "Python",
    title: "Problem I solved with Python",
    problem: "Needed to clean messy CSV data for a uni project.",
    solution: "Wrote a script to parse, filter and reformat it in seconds.",
    date: "Feb 4, 2025",
    tagColor: "#DCFCE7",
    tagText: "#15803d",
    accentColor: "#16a34a",
    iconColor: "#16a34a",
    bgColor: "#DCFCE7",
  },
  {
    id: 3,
    tag: "TypeScript",
    title: "Problem I solved with TypeScript",
    problem: "Kept getting runtime errors in a JavaScript project.",
    solution: "Migrated to TypeScript and caught every bug before the code ran.",
    date: "Jan 20, 2025",
    tagColor: "#FEF9C3",
    tagText: "#92400e",
    accentColor: "#ca8a04",
    iconColor: "#ca8a04",
    bgColor: "#FEF9C3",
  },
  {
    id: 4,
    tag: "CSS",
    title: "Problem I solved with CSS",
    problem: "Wanted a smooth card flip with zero JavaScript.",
    solution: "Used transform, backface-visibility and perspective. Pure CSS.",
    date: "Dec 9, 2024",
    tagColor: "#F3E8FF",
    tagText: "#7e22ce",
    accentColor: "#9333ea",
    iconColor: "#9333ea",
    bgColor: "#F3E8FF",
  },
];

export default cards;